name: watch_hub
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2
  get: ^4.7.1
  google_fonts: ^6.1.0

  # iOS-style icons
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/splash_screen_images/1.png
    - assets/splash_screen_images/2.png
    - assets/splash_screen_images/3.png
    - assets/svg/close-one.svg
    - assets/icon/google.png
    - assets/fonts/ 

  # Custom Fonts (Poppins)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/mainlogo.jpeg"